import React from "react";
import { VStack, Box, Grid } from "@chakra-ui/react";

import { GoBackButton } from "../components/input/GoBackButton";
import { SharedditLogo } from "../components/SharedditLogo";

export const DownloadImage: React.FC = () => {
  const src = localStorage.getItem("shareddit-image");
  if (src !== null) {
    return (
      <Grid p={3} minHeight="100vh">
        <VStack maxW="lg" marginX="auto" spacing={4}>
          <SharedditLogo />
          <Box fontSize="3xl">
            To download the image, right click the image (or long press on
            mobile) and select "Save image as" or "Copy image"
          </Box>
          <img src={src} alt="generated by shareddit" />
          <GoBackButton />
        </VStack>
      </Grid>
    );
  } else {
    window.location.href = "/";
    return <></>;
  }
};
